# Generated by Django 5.1.1 on 2024-09-25 21:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('invite_code', models.CharField(default='cFueMEzKr4', editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invite_expires_at', models.DateTimeField(default=datetime.datetime(2024, 10, 2, 17, 7, 24, 387488))),
                ('access_expires_at', models.DateTimeField(default=None, null=True)),
                ('assigned_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
