# Generated by Django 5.1.1 on 2024-09-25 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invite_code',
            field=models.CharField(default='7v6jqnrBsf', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='invite_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 2, 17, 12, 52, 158323)),
        ),
    ]
