# Generated by Django 5.1.1 on 2024-09-26 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_category_color_size_user_alter_invite_invite_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
        migrations.AlterField(
            model_name='invite',
            name='invite_code',
            field=models.CharField(default='F0UL0M5gA8', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='invite_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 2, 23, 34, 14, 928636)),
        ),
    ]
